---
name: "Format Rust code w/ clippy and rustfmt then test w/ cargo"
on: push

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                toolchain:
                    - stable
                    - beta

        steps:
            - uses: actions/checkout@v3
            - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
            - name: Build
              run: |
                rustup component add clippy
                rustup component add rustfmt
                cargo install cargo-audit
                cargo install cargo-outdated
                cargo build --verbose --release

            - name: Run rustfmt
              run: cargo fmt --all -- --check

            - name: Run clippy
              run: cargo clippy --all --all-targets --all-features -- -D warnings

            - name: Run cargo audit
              run: cargo audit

            - name: Run cargo outdated
              run: cargo outdated

            - name: Create log file
              run: touch bleulog.log

            - name: Run cargo test
              run: cargo test --quiet
